version: "3.9"
services:
  rest:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: "rest_api"
    ports:
      - "8090:8080"
    depends_on:
      - db
  db:
    image: mysql
    container_name: Rest_db-mysql
    privileged: true
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3302:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: WDC_MANAGER
    volumes:
      - ./storage:/var/lib/mysql